"""Add tenant_id to Task and Countdown models

Revision ID: f034151b82ef
Revises: af768be21212
Create Date: 2025-12-05 15:05:07.902135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f034151b82ef'
down_revision = 'af768be21212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add columns as nullable
    with op.batch_alter_table('countdowns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    # Populate tenant_id from related dashboard
    op.execute("""
        UPDATE countdowns 
        SET tenant_id = (
            SELECT tenant_id FROM dashboards 
            WHERE dashboards.id = countdowns.dashboard_id
        )
    """)
    
    op.execute("""
        UPDATE tasks 
        SET tenant_id = (
            SELECT tenant_id FROM dashboards 
            WHERE dashboards.id = tasks.dashboard_id
        )
    """)
    
    # Now make columns non-nullable and add indexes/constraints
    with op.batch_alter_table('countdowns', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        batch_op.create_index('idx_countdowns_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_countdowns_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_countdowns_tenant_id', 'families', ['tenant_id'], ['id'])

    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dashboards_tenant_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        batch_op.create_index('idx_tasks_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_tenant_id', 'families', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_tenant_id'))
        batch_op.drop_index('idx_tasks_tenant_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dashboards_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('countdowns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_countdowns_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_countdowns_tenant_id'))
        batch_op.drop_index('idx_countdowns_tenant_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
